services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cbs-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/bin/bash -c '</dev/tcp/localhost/1433'"]
      interval: 10s
      timeout: 5s
      retries: 30

  api:
    build:
      context: .
      dockerfile: CoreBankingSystem.Api/Dockerfile
    container_name: cbs-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sql;Database=CoreBankingSystem;User Id=sa;Password=Your_password123;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=true
    depends_on:
      sql:
        condition: service_healthy
    ports:
      - "8080:8080"

  web:
    build:
      context: CoreBankingSystem.AngularUI
      dockerfile: Dockerfile
    container_name: cbs-web
    depends_on:
      - api
    ports:
      - "8081:80"

volumes:
  sql_data:
