# escape=`
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY CoreBankingSystem.Api/CoreBankingSystem.Api.csproj CoreBankingSystem.Api/
COPY CoreBankingSystem.Application/CoreBankingSystem.Application.csproj CoreBankingSystem.Application/
COPY CoreBankingSystem.Persistence/CoreBankingSystem.Persistence.csproj CoreBankingSystem.Persistence/
COPY CoreBankingSystem.Domain/CoreBankingSystem.Domain.csproj CoreBankingSystem.Domain/
RUN dotnet restore CoreBankingSystem.Api/CoreBankingSystem.Api.csproj

COPY . .
WORKDIR /src/CoreBankingSystem.Api
RUN dotnet publish CoreBankingSystem.Api.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080 \
    ASPNETCORE_ENVIRONMENT=Production
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "CoreBankingSystem.Api.dll"]
