FROM node:20-alpine AS build
WORKDIR /app
COPY CoreBankingSystem.AngularUI/package*.json ./
RUN npm ci
COPY CoreBankingSystem.AngularUI/ ./
RUN npm run build

FROM nginx:1.27-alpine
COPY CoreBankingSystem.AngularUI/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/core-banking-system.angular-ui/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
